// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxljsfcmhiuqssireuys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94bGpzZmNtaGl1cXNzaXJldXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MzAxOTUsImV4cCI6MjA2NDQwNjE5NX0._CPU_02E593xyepqO6ueMEgleDmI0_aJoCDlqknTLyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);